// Icon mapping component for Font Awesome icons
const Icon = ({ name, className = "", ...props }) => {
  const iconMap = {
    'home': 'fas fa-home',
    'book-open': 'fas fa-book-open',
    'file-text': 'fas fa-file-alt',
    'info': 'fas fa-info-circle',
    'mail': 'fas fa-envelope',
    'graduation-cap': 'fas fa-graduation-cap',
    'arrow-left': 'fas fa-arrow-left',
    'arrow-right': 'fas fa-arrow-right',
    'clock': 'fas fa-clock',
    'filter': 'fas fa-filter',
    'lightbulb': 'fas fa-lightbulb',
    'award': 'fas fa-award',
    'hourglass': 'fas fa-hourglass',
    'upload': 'fas fa-upload',
    'book': 'fas fa-book',
    'calendar': 'fas fa-calendar',
    'code': 'fas fa-code',
    'flask-conical': 'fas fa-flask',
    'users': 'fas fa-users',
    'sun': 'fas fa-sun',
    'moon': 'fas fa-moon',
    'github': 'fab fa-github',
    'linkedin': 'fab fa-linkedin-in',
    'twitter': 'fab fa-twitter',
    'external-link': 'fas fa-external-link-alt',
    'layers': 'fas fa-layer-group',
    'folder-open': 'fas fa-folder-open',
    'search': 'fas fa-search',
    'check': 'fas fa-check',
    'calculator': 'fas fa-calculator',
    'microchip': 'fas fa-microchip',
    'database': 'fas fa-database',
    'network-wired': 'fas fa-network-wired',
    'code-branch': 'fas fa-code-branch',
    'laptop-code': 'fas fa-laptop-code',
    'globe': 'fas fa-globe',
    'chart-bar': 'fas fa-chart-bar',
    'brain': 'fas fa-brain',
    'shield-alt': 'fas fa-shield-alt',
    'cloud': 'fas fa-cloud',
    'mobile-alt': 'fas fa-mobile-alt',
    'project-diagram': 'fas fa-project-diagram',
    'comments': 'fas fa-comments',
    'robot': 'fas fa-robot',
    'dna': 'fas fa-dna',
    'users-cog': 'fas fa-users-cog',
    'lock': 'fas fa-lock',
    'image': 'fas fa-image',
    'chart-network': 'fas fa-project-diagram',
    'cogs': 'fas fa-cogs',
    'server': 'fas fa-server',
    'desktop': 'fas fa-desktop',
    'graduation-cap': 'fas fa-graduation-cap',
    'presentation': 'fas fa-presentation',
    'folder': 'fas fa-folder',
    'lightbulb': 'fas fa-lightbulb',
    'award': 'fas fa-award',
    'heart': 'fas fa-heart',
    'shield': 'fas fa-shield-alt',
    'zap': 'fas fa-bolt',
    'handshake': 'fas fa-handshake',
    'star': 'fas fa-star',
    'rocket': 'fas fa-rocket',
    'code-branch': 'fas fa-code-branch',
    'user-plus': 'fas fa-user-plus',
    'file-alt': 'fas fa-file-alt',
    'trophy': 'fas fa-trophy',
    'menu': 'fas fa-bars',
    'times': 'fas fa-times',
    'clipboard-list': 'fas fa-clipboard-list',
    'list': 'fas fa-list',
    'download': 'fas fa-download',
    'calculator': 'fas fa-calculator',
    'microchip': 'fas fa-microchip',
    'laptop-code': 'fas fa-laptop-code',
    'database': 'fas fa-database',
    'network-wired': 'fas fa-network-wired',
    'globe': 'fas fa-globe',
    'mobile-alt': 'fas fa-mobile-alt',
    'chart-bar': 'fas fa-chart-bar',
    'brain': 'fas fa-brain',
    'lock': 'fas fa-lock',
    'cloud': 'fas fa-cloud',
    'server': 'fas fa-server',
    'image': 'fas fa-image',
    'users-cog': 'fas fa-users-cog',
    'dna': 'fas fa-dna',
    'chart-network': 'fas fa-project-diagram',
    'graduation-cap': 'fas fa-graduation-cap'
  };

  const iconClass = iconMap[name] || `fas fa-${name}`;
  
  return React.createElement('i', {
    className: `${iconClass} ${className}`,
    ...props
  });
};

// Make Icon component globally available
window.Icon = Icon;
